bracketSpacing: false
proseWrap: always
singleQuote: true
trailingComma: all

# You can remove these overrides if you like TypeScript at 80 width
overrides:
  - files: '*.ts'
    options:
      printWidth: 120
  - files: '*.tsx'
    options:
      printWidth: 120
